version: '3.8'

services:
  main-controller-server:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5001:5000"

networks:
  default:
    external: true
    name: local_environment_network
