version: '3.8'

services:
  flask-server:
    build: .
    image: "eu.gcr.io/finalyearproject-338819/fyp_instance"
    volumes:
      - ./:/app
    ports:
      - "6000-6001:5000"
    expose:
      - "5000"

networks:
  default:
    external: true
    name: local_environment_network
