version: '3.8'

services:
  flask-server:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
