version: '3.8'

services:
  flask-server:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
  # TODO: Might become useful as a message queue later on
  # redis:
  #   image: redis
  #   container_name: redis-server
  #   ports:
  #     - "6379:6379"
