version: '3.8'

services:
  flask-server:
    build: .
    image: "local_fyp_instance"
    volumes:
      - ./:/app
    ports:
      - "5000-5001:5000"
    expose:
      - "5000"

networks:
  default:
    external: true
    name: local_environment_network
